version: '2.3'
services:
  oracledb:
    image: store/oracle/database-enterprise:12.2.0.1
    restart: on-failure
# Uncomment if you need volumes
#    volumes:
#    - "/data/OracleDBData:/ORCL store/oracle/database-enterprise:12.2.0.1"
    ports:
    - "1521:1521"
    - "5500:5500"

  aggregator:
    build: .
    restart: on-failure
    depends_on:
      oracledb:
        condition: service_healthy
    links:
    - oracledb
    ports:
    - "8080:8080"