version: '3.1'
services:
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    restart: always
#    volumes:
#    - "/data/OracleDBData:/ORCL store/oracle/database-enterprise:12.2.0.1"
    ports:
    - "32769:1521"
    - "32768:5500"
  aggregator:
    build: .
    image: oracle-aggregator
    restart: always
    links:
    - oracle
    ports:
    - "8080:8080"