version: '2.3'
services:
#  oracledb:
#    image: store/oracle/database-enterprise:12.2.0.1
#    restart: on-failure
#    volumes: #Uncomment if you need volumes
#    - "/data/OracleDBData:/ORCL store/oracle/database-enterprise:12.2.0.1"
#    ports:
#    - "32769:1521"
#    - "32768:5500"

  aggregator:
    restart: on-failure
    build: ./aggregator
    ports:
    - "24010:8080"
#    depends_on:
#      oracledb:
#        condition: service_healthy
#    links:
#      - oracledb

#  oracle_provider:
#    restart: on-failure
#    build: ./provider
#    ports:
#    - "24011:8080"
