spring:
  profiles:
    active: "local"
server:
  port: 8080

---

spring:
  profiles: local
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  datasource:
    url: ${PG_USER}
    username: ${PG_USER}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  profiles: prod
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  datasource:
    url: ${PG_USER}
    username: ${PG_USER}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect

